### ISSUE TITLE
Not able to run

### ISSUE THREAD

**Issue by k-rajmani2k** [1tomy1/clusteringAlgorithms#1]
i am unable to run it can you help getting some errors and which ide should i use

**Comment by tomijerenko** [comment]
The IDE doesn't matter. What exactly are you trying to achieve?

The command for executing code is, for example, ```python3 0_read.py 1_pug.jpg | python3 0_kmeans.py 2 | python3 0_save.py 2_pug2means.jpg``` on Linux/Mac. ```0_read.py``` transforms 3 or 4 channel image into vector array, which is input to ```0_kmeans.py```, calculating segmented vector array, which is piped to ```0_save.py```  to save the vector array as an image.

This project is by no means optimized implementation of the two algorithms. If you need optimized solutions, you're better off using a library like scikit-learn.

**Comment by k-rajmani2k** [comment]
actually when i am running python 0_read.py in pycharm then filename then its's  saying no file exits

**Comment by k-rajmani2k** [comment]
will it work on jupyter notebook

**Comment by tomijerenko** [comment]
You need to provide 3 or 4 channel image path as first argument to ```0_read.py```. It runs on every system supporting python. It seems to me that you have problems understanding how Linux command line works. Read about the following topics online: command redirection, pipelines, standard input, standard output, arguments. I'm closing this issue, because it's not code related.
